# Generated by Django 6.0.2 on 2026-03-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0002_alter_answer_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='author_tier',
            field=models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Diamond', 'Diamond'), ('Challenger', 'Challenger')], default='Bronze', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='author_tier',
            field=models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Diamond', 'Diamond'), ('Challenger', 'Challenger')], default='Bronze', max_length=20),
        ),
    ]
