# Generated by Django 6.0.2 on 2026-03-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0003_answer_author_tier_question_author_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='author_tier',
            field=models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Diamond', 'Diamond'), ('Master', 'Master'), ('Challenger', 'Challenger')], default='Bronze', max_length=20),
        ),
        migrations.AlterField(
            model_name='arenaprofile',
            name='tier',
            field=models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Diamond', 'Diamond'), ('Master', 'Master'), ('Challenger', 'Challenger')], default='Bronze', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='author_tier',
            field=models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Diamond', 'Diamond'), ('Master', 'Master'), ('Challenger', 'Challenger')], default='Bronze', max_length=20),
        ),
    ]
