# Generated by Django 6.0.2 on 2026-03-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0004_alter_answer_author_tier_alter_arenaprofile_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arenaprofile',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
