# Generated by Django 6.0.2 on 2026-03-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0005_arenaprofile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arenaprofile',
            name='nickname',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30),
        ),
    ]
